instance_transforms:
  _target_: src.transforms.mel_spectrogram.MelSpectrogramTransform
  config:
    _target_: src.transforms.mel_spectrogram.MelSpectrogramConfig
    sample_rate: 22050
    n_fft: 1024
    win_length: 1024
    hop_length: 256
    n_mels: 80
    f_min: 0
    f_max: 8000

batch_transforms: {}